# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Windows Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  list-tests:
    runs-on: windows-latest
    needs: build
    outputs: 
      test-matrix: ${{ steps.set-matrix.outputs.test-matrix }}
      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 9.0.x
      - id: set-matrix
        shell: pwsh
        run: ./scripts/ci/extract_test_names_to_json.ps1
  test:
    runs-on: windows-latest
    needs: [build, list-tests]
    
    # Creates one job per test defined in code.
    strategy: 
      fail-fast: false
      matrix: 
        testName: ${{ fromJson(needs.list-tests.outputs.test-matrix) }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      # Run each test.
      - name: Run ${{ matrix.testName }}
        run: | 
          dotnet test dotPerfStatTest/dotPerfStatTest.csproj \
            --no-build \
            --configuration Release \
            --filter "FullyQualifiedName~${{ matrix.testName }}"
