# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Windows Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  list-tests:
    runs-on: windows-latest
    needs: build
    outputs: 
      test-matrix: ${{ steps.set-matrix.outputs.text-matrix }}
      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 9.0.x
      - id: set-matrix
        shell: pwsh
        run: |
          # 1️⃣ List all tests (quiet console output + list-tests)
          $raw = dotnet test dotPerfStatTest/dotPerfStatTest.csproj `
            -p:TestingPlatformCaptureOutput=false -- `
            --list-tests --no-build `
            --logger "console;verbosity=quiet"
          
          # 2️⃣ Split into lines, then skip everything up to the header
          $lines   = $raw -split "`r?`n"
          $started = $false
          $tests   = @()
          foreach ($line in $lines) {
            if (-not $started) {
              if ($line -match '^The following Tests are available:') {
                $started = $true
                continue
              }
            }
            elseif ($line.Trim()) {
              $tests += $line.Trim()
            }
          }
          
          # 3️⃣ Pack into JSON array
          $json = $tests | ConvertTo-Json -Compress
          
          # 4️⃣ Emit for GitHub Actions (modern syntax)
          "test-matrix=$json" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          Write-Host $json
  test:
    runs-on: windows-latest
    needs: [build, list-tests]
    
    # Creates one job per test defined in code.
    strategy: 
      fail-fast: false
      matrix: 
        testName: ${{ fromJson(needs.list-tests.output.test-matrix) }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      # Run each test.
      - name: Run ${{ matrix.testName }}
        run: | 
          dotnet test dotPerfStatTest/dotPerfStatTest.csproj \
            --no-build \
            --configuration Release \
            --filter "FullyQualifiedName~${{ matrix.testName }}
